# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'HardDriveInputArgs',
    'HardDriveInputArgsDict',
]

MYPY = False

if not MYPY:
    class HardDriveInputArgsDict(TypedDict):
        controller_location: pulumi.Input[builtins.int]
        controller_number: pulumi.Input[builtins.int]
        controller_type: pulumi.Input[builtins.str]
        path: pulumi.Input[builtins.str]
elif False:
    HardDriveInputArgsDict: TypeAlias = Mapping[str, Any]

@pulumi.input_type
class HardDriveInputArgs:
    def __init__(__self__, *,
                 controller_location: pulumi.Input[builtins.int],
                 controller_number: pulumi.Input[builtins.int],
                 controller_type: pulumi.Input[builtins.str],
                 path: pulumi.Input[builtins.str]):
        pulumi.set(__self__, "controller_location", controller_location)
        pulumi.set(__self__, "controller_number", controller_number)
        pulumi.set(__self__, "controller_type", controller_type)
        pulumi.set(__self__, "path", path)

    @property
    @pulumi.getter(name="controllerLocation")
    def controller_location(self) -> pulumi.Input[builtins.int]:
        return pulumi.get(self, "controller_location")

    @controller_location.setter
    def controller_location(self, value: pulumi.Input[builtins.int]):
        pulumi.set(self, "controller_location", value)

    @property
    @pulumi.getter(name="controllerNumber")
    def controller_number(self) -> pulumi.Input[builtins.int]:
        return pulumi.get(self, "controller_number")

    @controller_number.setter
    def controller_number(self, value: pulumi.Input[builtins.int]):
        pulumi.set(self, "controller_number", value)

    @property
    @pulumi.getter(name="controllerType")
    def controller_type(self) -> pulumi.Input[builtins.str]:
        return pulumi.get(self, "controller_type")

    @controller_type.setter
    def controller_type(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "controller_type", value)

    @property
    @pulumi.getter
    def path(self) -> pulumi.Input[builtins.str]:
        return pulumi.get(self, "path")

    @path.setter
    def path(self, value: pulumi.Input[builtins.str]):
        pulumi.set(self, "path", value)


