// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Hyperv.Machine.Inputs
{

    public sealed class HardDriveInputArgs : global::Pulumi.ResourceArgs
    {
        [Input("controllerLocation", required: true)]
        public Input<int> ControllerLocation { get; set; } = null!;

        [Input("controllerNumber", required: true)]
        public Input<int> ControllerNumber { get; set; } = null!;

        [Input("controllerType", required: true)]
        public Input<string> ControllerType { get; set; } = null!;

        [Input("path", required: true)]
        public Input<string> Path { get; set; } = null!;

        public HardDriveInputArgs()
        {
        }
        public static new HardDriveInputArgs Empty => new HardDriveInputArgs();
    }
}
