# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_hyperv.config as __config
    config = __config
    import pulumi_hyperv.machine as __machine
    machine = __machine
    import pulumi_hyperv.networkadapter as __networkadapter
    networkadapter = __networkadapter
    import pulumi_hyperv.vhdfile as __vhdfile
    vhdfile = __vhdfile
    import pulumi_hyperv.virtualswitch as __virtualswitch
    virtualswitch = __virtualswitch
else:
    config = _utilities.lazy_import('pulumi_hyperv.config')
    machine = _utilities.lazy_import('pulumi_hyperv.machine')
    networkadapter = _utilities.lazy_import('pulumi_hyperv.networkadapter')
    vhdfile = _utilities.lazy_import('pulumi_hyperv.vhdfile')
    virtualswitch = _utilities.lazy_import('pulumi_hyperv.virtualswitch')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "hyperv",
  "mod": "machine",
  "fqn": "pulumi_hyperv.machine",
  "classes": {
   "hyperv:machine:Machine": "Machine"
  }
 },
 {
  "pkg": "hyperv",
  "mod": "networkadapter",
  "fqn": "pulumi_hyperv.networkadapter",
  "classes": {
   "hyperv:networkadapter:NetworkAdapter": "NetworkAdapter"
  }
 },
 {
  "pkg": "hyperv",
  "mod": "vhdfile",
  "fqn": "pulumi_hyperv.vhdfile",
  "classes": {
   "hyperv:vhdfile:VhdFile": "VhdFile"
  }
 },
 {
  "pkg": "hyperv",
  "mod": "virtualswitch",
  "fqn": "pulumi_hyperv.virtualswitch",
  "classes": {
   "hyperv:virtualswitch:VirtualSwitch": "VirtualSwitch"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "hyperv",
  "token": "pulumi:providers:hyperv",
  "fqn": "pulumi_hyperv",
  "class": "Provider"
 }
]
"""
)
