// *** WARNING: this file was generated by pulumi. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Hyperv.Machine.Outputs
{

    [OutputType]
    public sealed class HardDriveInput
    {
        public readonly int ControllerLocation;
        public readonly int ControllerNumber;
        public readonly string ControllerType;
        public readonly string Path;

        [OutputConstructor]
        private HardDriveInput(
            int controllerLocation,

            int controllerNumber,

            string controllerType,

            string path)
        {
            ControllerLocation = controllerLocation;
            ControllerNumber = controllerNumber;
            ControllerType = controllerType;
            Path = path;
        }
    }
}
