// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.hyperv.machine;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.hyperv.machine.inputs.HardDriveInputArgs;
import com.pulumi.hyperv.networkadapter.inputs.NetworkAdapterInputsArgs;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class MachineArgs extends com.pulumi.resources.ResourceArgs {

    public static final MachineArgs Empty = new MachineArgs();

    /**
     * The action to take when the host starts. Valid values are Nothing, StartIfRunning, and Start. Defaults to Nothing.
     * 
     */
    @Import(name="autoStartAction")
    private @Nullable Output<String> autoStartAction;

    /**
     * @return The action to take when the host starts. Valid values are Nothing, StartIfRunning, and Start. Defaults to Nothing.
     * 
     */
    public Optional<Output<String>> autoStartAction() {
        return Optional.ofNullable(this.autoStartAction);
    }

    /**
     * The action to take when the host shuts down. Valid values are TurnOff, Save, and ShutDown. Defaults to TurnOff.
     * 
     */
    @Import(name="autoStopAction")
    private @Nullable Output<String> autoStopAction;

    /**
     * @return The action to take when the host shuts down. Valid values are TurnOff, Save, and ShutDown. Defaults to TurnOff.
     * 
     */
    public Optional<Output<String>> autoStopAction() {
        return Optional.ofNullable(this.autoStopAction);
    }

    /**
     * The command to run on create.
     * 
     */
    @Import(name="create")
    private @Nullable Output<String> create;

    /**
     * @return The command to run on create.
     * 
     */
    public Optional<Output<String>> create() {
        return Optional.ofNullable(this.create);
    }

    /**
     * The command to run on delete. The environment variables PULUMI_COMMAND_STDOUT
     * and PULUMI_COMMAND_STDERR are set to the stdout and stderr properties of the
     * Command resource from previous create or update steps.
     * 
     */
    @Import(name="delete")
    private @Nullable Output<String> delete;

    /**
     * @return The command to run on delete. The environment variables PULUMI_COMMAND_STDOUT
     * and PULUMI_COMMAND_STDERR are set to the stdout and stderr properties of the
     * Command resource from previous create or update steps.
     * 
     */
    public Optional<Output<String>> delete() {
        return Optional.ofNullable(this.delete);
    }

    /**
     * Whether to enable dynamic memory for the Virtual Machine. Defaults to false.
     * 
     */
    @Import(name="dynamicMemory")
    private @Nullable Output<Boolean> dynamicMemory;

    /**
     * @return Whether to enable dynamic memory for the Virtual Machine. Defaults to false.
     * 
     */
    public Optional<Output<Boolean>> dynamicMemory() {
        return Optional.ofNullable(this.dynamicMemory);
    }

    /**
     * Generation of the Virtual Machine. Defaults to 2.
     * 
     */
    @Import(name="generation")
    private @Nullable Output<Integer> generation;

    /**
     * @return Generation of the Virtual Machine. Defaults to 2.
     * 
     */
    public Optional<Output<Integer>> generation() {
        return Optional.ofNullable(this.generation);
    }

    /**
     * Hard drives to attach to the Virtual Machine.
     * 
     */
    @Import(name="hardDrives")
    private @Nullable Output<List<HardDriveInputArgs>> hardDrives;

    /**
     * @return Hard drives to attach to the Virtual Machine.
     * 
     */
    public Optional<Output<List<HardDriveInputArgs>>> hardDrives() {
        return Optional.ofNullable(this.hardDrives);
    }

    /**
     * Name of the Virtual Machine
     * 
     */
    @Import(name="machineName")
    private @Nullable Output<String> machineName;

    /**
     * @return Name of the Virtual Machine
     * 
     */
    public Optional<Output<String>> machineName() {
        return Optional.ofNullable(this.machineName);
    }

    /**
     * Maximum amount of memory that can be allocated to the Virtual Machine in MB when using dynamic memory.
     * 
     */
    @Import(name="maximumMemory")
    private @Nullable Output<Integer> maximumMemory;

    /**
     * @return Maximum amount of memory that can be allocated to the Virtual Machine in MB when using dynamic memory.
     * 
     */
    public Optional<Output<Integer>> maximumMemory() {
        return Optional.ofNullable(this.maximumMemory);
    }

    /**
     * Amount of memory to allocate to the Virtual Machine in MB. Defaults to 1024.
     * 
     */
    @Import(name="memorySize")
    private @Nullable Output<Integer> memorySize;

    /**
     * @return Amount of memory to allocate to the Virtual Machine in MB. Defaults to 1024.
     * 
     */
    public Optional<Output<Integer>> memorySize() {
        return Optional.ofNullable(this.memorySize);
    }

    /**
     * Minimum amount of memory to allocate to the Virtual Machine in MB when using dynamic memory.
     * 
     */
    @Import(name="minimumMemory")
    private @Nullable Output<Integer> minimumMemory;

    /**
     * @return Minimum amount of memory to allocate to the Virtual Machine in MB when using dynamic memory.
     * 
     */
    public Optional<Output<Integer>> minimumMemory() {
        return Optional.ofNullable(this.minimumMemory);
    }

    /**
     * Network adapters to attach to the Virtual Machine.
     * 
     */
    @Import(name="networkAdapters")
    private @Nullable Output<List<NetworkAdapterInputsArgs>> networkAdapters;

    /**
     * @return Network adapters to attach to the Virtual Machine.
     * 
     */
    public Optional<Output<List<NetworkAdapterInputsArgs>>> networkAdapters() {
        return Optional.ofNullable(this.networkAdapters);
    }

    /**
     * Number of processors to allocate to the Virtual Machine. Defaults to 1.
     * 
     */
    @Import(name="processorCount")
    private @Nullable Output<Integer> processorCount;

    /**
     * @return Number of processors to allocate to the Virtual Machine. Defaults to 1.
     * 
     */
    public Optional<Output<Integer>> processorCount() {
        return Optional.ofNullable(this.processorCount);
    }

    /**
     * Trigger a resource replacement on changes to any of these values. The
     * trigger values can be of any type. If a value is different in the current update compared to the
     * previous update, the resource will be replaced, i.e., the &#34;create&#34; command will be re-run.
     * Please see the resource documentation for examples.
     * 
     */
    @Import(name="triggers")
    private @Nullable Output<List<Object>> triggers;

    /**
     * @return Trigger a resource replacement on changes to any of these values. The
     * trigger values can be of any type. If a value is different in the current update compared to the
     * previous update, the resource will be replaced, i.e., the &#34;create&#34; command will be re-run.
     * Please see the resource documentation for examples.
     * 
     */
    public Optional<Output<List<Object>>> triggers() {
        return Optional.ofNullable(this.triggers);
    }

    /**
     * The command to run on update, if empty, create will
     * run again. The environment variables PULUMI_COMMAND_STDOUT and PULUMI_COMMAND_STDERR
     * are set to the stdout and stderr properties of the Command resource from previous
     * create or update steps.
     * 
     */
    @Import(name="update")
    private @Nullable Output<String> update;

    /**
     * @return The command to run on update, if empty, create will
     * run again. The environment variables PULUMI_COMMAND_STDOUT and PULUMI_COMMAND_STDERR
     * are set to the stdout and stderr properties of the Command resource from previous
     * create or update steps.
     * 
     */
    public Optional<Output<String>> update() {
        return Optional.ofNullable(this.update);
    }

    private MachineArgs() {}

    private MachineArgs(MachineArgs $) {
        this.autoStartAction = $.autoStartAction;
        this.autoStopAction = $.autoStopAction;
        this.create = $.create;
        this.delete = $.delete;
        this.dynamicMemory = $.dynamicMemory;
        this.generation = $.generation;
        this.hardDrives = $.hardDrives;
        this.machineName = $.machineName;
        this.maximumMemory = $.maximumMemory;
        this.memorySize = $.memorySize;
        this.minimumMemory = $.minimumMemory;
        this.networkAdapters = $.networkAdapters;
        this.processorCount = $.processorCount;
        this.triggers = $.triggers;
        this.update = $.update;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(MachineArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private MachineArgs $;

        public Builder() {
            $ = new MachineArgs();
        }

        public Builder(MachineArgs defaults) {
            $ = new MachineArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param autoStartAction The action to take when the host starts. Valid values are Nothing, StartIfRunning, and Start. Defaults to Nothing.
         * 
         * @return builder
         * 
         */
        public Builder autoStartAction(@Nullable Output<String> autoStartAction) {
            $.autoStartAction = autoStartAction;
            return this;
        }

        /**
         * @param autoStartAction The action to take when the host starts. Valid values are Nothing, StartIfRunning, and Start. Defaults to Nothing.
         * 
         * @return builder
         * 
         */
        public Builder autoStartAction(String autoStartAction) {
            return autoStartAction(Output.of(autoStartAction));
        }

        /**
         * @param autoStopAction The action to take when the host shuts down. Valid values are TurnOff, Save, and ShutDown. Defaults to TurnOff.
         * 
         * @return builder
         * 
         */
        public Builder autoStopAction(@Nullable Output<String> autoStopAction) {
            $.autoStopAction = autoStopAction;
            return this;
        }

        /**
         * @param autoStopAction The action to take when the host shuts down. Valid values are TurnOff, Save, and ShutDown. Defaults to TurnOff.
         * 
         * @return builder
         * 
         */
        public Builder autoStopAction(String autoStopAction) {
            return autoStopAction(Output.of(autoStopAction));
        }

        /**
         * @param create The command to run on create.
         * 
         * @return builder
         * 
         */
        public Builder create(@Nullable Output<String> create) {
            $.create = create;
            return this;
        }

        /**
         * @param create The command to run on create.
         * 
         * @return builder
         * 
         */
        public Builder create(String create) {
            return create(Output.of(create));
        }

        /**
         * @param delete The command to run on delete. The environment variables PULUMI_COMMAND_STDOUT
         * and PULUMI_COMMAND_STDERR are set to the stdout and stderr properties of the
         * Command resource from previous create or update steps.
         * 
         * @return builder
         * 
         */
        public Builder delete(@Nullable Output<String> delete) {
            $.delete = delete;
            return this;
        }

        /**
         * @param delete The command to run on delete. The environment variables PULUMI_COMMAND_STDOUT
         * and PULUMI_COMMAND_STDERR are set to the stdout and stderr properties of the
         * Command resource from previous create or update steps.
         * 
         * @return builder
         * 
         */
        public Builder delete(String delete) {
            return delete(Output.of(delete));
        }

        /**
         * @param dynamicMemory Whether to enable dynamic memory for the Virtual Machine. Defaults to false.
         * 
         * @return builder
         * 
         */
        public Builder dynamicMemory(@Nullable Output<Boolean> dynamicMemory) {
            $.dynamicMemory = dynamicMemory;
            return this;
        }

        /**
         * @param dynamicMemory Whether to enable dynamic memory for the Virtual Machine. Defaults to false.
         * 
         * @return builder
         * 
         */
        public Builder dynamicMemory(Boolean dynamicMemory) {
            return dynamicMemory(Output.of(dynamicMemory));
        }

        /**
         * @param generation Generation of the Virtual Machine. Defaults to 2.
         * 
         * @return builder
         * 
         */
        public Builder generation(@Nullable Output<Integer> generation) {
            $.generation = generation;
            return this;
        }

        /**
         * @param generation Generation of the Virtual Machine. Defaults to 2.
         * 
         * @return builder
         * 
         */
        public Builder generation(Integer generation) {
            return generation(Output.of(generation));
        }

        /**
         * @param hardDrives Hard drives to attach to the Virtual Machine.
         * 
         * @return builder
         * 
         */
        public Builder hardDrives(@Nullable Output<List<HardDriveInputArgs>> hardDrives) {
            $.hardDrives = hardDrives;
            return this;
        }

        /**
         * @param hardDrives Hard drives to attach to the Virtual Machine.
         * 
         * @return builder
         * 
         */
        public Builder hardDrives(List<HardDriveInputArgs> hardDrives) {
            return hardDrives(Output.of(hardDrives));
        }

        /**
         * @param hardDrives Hard drives to attach to the Virtual Machine.
         * 
         * @return builder
         * 
         */
        public Builder hardDrives(HardDriveInputArgs... hardDrives) {
            return hardDrives(List.of(hardDrives));
        }

        /**
         * @param machineName Name of the Virtual Machine
         * 
         * @return builder
         * 
         */
        public Builder machineName(@Nullable Output<String> machineName) {
            $.machineName = machineName;
            return this;
        }

        /**
         * @param machineName Name of the Virtual Machine
         * 
         * @return builder
         * 
         */
        public Builder machineName(String machineName) {
            return machineName(Output.of(machineName));
        }

        /**
         * @param maximumMemory Maximum amount of memory that can be allocated to the Virtual Machine in MB when using dynamic memory.
         * 
         * @return builder
         * 
         */
        public Builder maximumMemory(@Nullable Output<Integer> maximumMemory) {
            $.maximumMemory = maximumMemory;
            return this;
        }

        /**
         * @param maximumMemory Maximum amount of memory that can be allocated to the Virtual Machine in MB when using dynamic memory.
         * 
         * @return builder
         * 
         */
        public Builder maximumMemory(Integer maximumMemory) {
            return maximumMemory(Output.of(maximumMemory));
        }

        /**
         * @param memorySize Amount of memory to allocate to the Virtual Machine in MB. Defaults to 1024.
         * 
         * @return builder
         * 
         */
        public Builder memorySize(@Nullable Output<Integer> memorySize) {
            $.memorySize = memorySize;
            return this;
        }

        /**
         * @param memorySize Amount of memory to allocate to the Virtual Machine in MB. Defaults to 1024.
         * 
         * @return builder
         * 
         */
        public Builder memorySize(Integer memorySize) {
            return memorySize(Output.of(memorySize));
        }

        /**
         * @param minimumMemory Minimum amount of memory to allocate to the Virtual Machine in MB when using dynamic memory.
         * 
         * @return builder
         * 
         */
        public Builder minimumMemory(@Nullable Output<Integer> minimumMemory) {
            $.minimumMemory = minimumMemory;
            return this;
        }

        /**
         * @param minimumMemory Minimum amount of memory to allocate to the Virtual Machine in MB when using dynamic memory.
         * 
         * @return builder
         * 
         */
        public Builder minimumMemory(Integer minimumMemory) {
            return minimumMemory(Output.of(minimumMemory));
        }

        /**
         * @param networkAdapters Network adapters to attach to the Virtual Machine.
         * 
         * @return builder
         * 
         */
        public Builder networkAdapters(@Nullable Output<List<NetworkAdapterInputsArgs>> networkAdapters) {
            $.networkAdapters = networkAdapters;
            return this;
        }

        /**
         * @param networkAdapters Network adapters to attach to the Virtual Machine.
         * 
         * @return builder
         * 
         */
        public Builder networkAdapters(List<NetworkAdapterInputsArgs> networkAdapters) {
            return networkAdapters(Output.of(networkAdapters));
        }

        /**
         * @param networkAdapters Network adapters to attach to the Virtual Machine.
         * 
         * @return builder
         * 
         */
        public Builder networkAdapters(NetworkAdapterInputsArgs... networkAdapters) {
            return networkAdapters(List.of(networkAdapters));
        }

        /**
         * @param processorCount Number of processors to allocate to the Virtual Machine. Defaults to 1.
         * 
         * @return builder
         * 
         */
        public Builder processorCount(@Nullable Output<Integer> processorCount) {
            $.processorCount = processorCount;
            return this;
        }

        /**
         * @param processorCount Number of processors to allocate to the Virtual Machine. Defaults to 1.
         * 
         * @return builder
         * 
         */
        public Builder processorCount(Integer processorCount) {
            return processorCount(Output.of(processorCount));
        }

        /**
         * @param triggers Trigger a resource replacement on changes to any of these values. The
         * trigger values can be of any type. If a value is different in the current update compared to the
         * previous update, the resource will be replaced, i.e., the &#34;create&#34; command will be re-run.
         * Please see the resource documentation for examples.
         * 
         * @return builder
         * 
         */
        public Builder triggers(@Nullable Output<List<Object>> triggers) {
            $.triggers = triggers;
            return this;
        }

        /**
         * @param triggers Trigger a resource replacement on changes to any of these values. The
         * trigger values can be of any type. If a value is different in the current update compared to the
         * previous update, the resource will be replaced, i.e., the &#34;create&#34; command will be re-run.
         * Please see the resource documentation for examples.
         * 
         * @return builder
         * 
         */
        public Builder triggers(List<Object> triggers) {
            return triggers(Output.of(triggers));
        }

        /**
         * @param triggers Trigger a resource replacement on changes to any of these values. The
         * trigger values can be of any type. If a value is different in the current update compared to the
         * previous update, the resource will be replaced, i.e., the &#34;create&#34; command will be re-run.
         * Please see the resource documentation for examples.
         * 
         * @return builder
         * 
         */
        public Builder triggers(Object... triggers) {
            return triggers(List.of(triggers));
        }

        /**
         * @param update The command to run on update, if empty, create will
         * run again. The environment variables PULUMI_COMMAND_STDOUT and PULUMI_COMMAND_STDERR
         * are set to the stdout and stderr properties of the Command resource from previous
         * create or update steps.
         * 
         * @return builder
         * 
         */
        public Builder update(@Nullable Output<String> update) {
            $.update = update;
            return this;
        }

        /**
         * @param update The command to run on update, if empty, create will
         * run again. The environment variables PULUMI_COMMAND_STDOUT and PULUMI_COMMAND_STDERR
         * are set to the stdout and stderr properties of the Command resource from previous
         * create or update steps.
         * 
         * @return builder
         * 
         */
        public Builder update(String update) {
            return update(Output.of(update));
        }

        public MachineArgs build() {
            return $;
        }
    }

}
