// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export namespace machine {
    export interface HardDriveInputArgs {
        controllerLocation: pulumi.Input<number>;
        controllerNumber: pulumi.Input<number>;
        controllerType: pulumi.Input<string>;
        path: pulumi.Input<string>;
    }
}

export namespace networkadapter {
    export interface NetworkAdapterInputsArgs {
        /**
         * The command to run on create.
         */
        create?: pulumi.Input<string>;
        /**
         * The command to run on delete. The environment variables PULUMI_COMMAND_STDOUT
         * and PULUMI_COMMAND_STDERR are set to the stdout and stderr properties of the
         * Command resource from previous create or update steps.
         */
        delete?: pulumi.Input<string>;
        /**
         * Enable DHCP Guard. Prevents the virtual machine from broadcasting DHCP server messages.
         */
        dhcpGuard?: pulumi.Input<boolean>;
        /**
         * Enable IEEE Priority Tagging. Allows the virtual machine to tag outgoing network traffic with an IEEE 802.1p priority value.
         */
        ieeePriorityTag?: pulumi.Input<boolean>;
        /**
         * Comma-separated list of IP addresses to assign to the network adapter.
         */
        ipAddresses?: pulumi.Input<string>;
        /**
         * MAC address for the network adapter. If not specified, a dynamic MAC address will be generated.
         */
        macAddress?: pulumi.Input<string>;
        /**
         * Name of the network adapter
         */
        name: pulumi.Input<string>;
        /**
         * Port mirroring mode. Valid values are None, Source, Destination, and Both. Defaults to None.
         */
        portMirroring?: pulumi.Input<string>;
        /**
         * Enable Router Guard. Prevents the virtual machine from broadcasting router advertisement and discovery messages.
         */
        routerGuard?: pulumi.Input<boolean>;
        /**
         * Name of the virtual switch to connect the network adapter to
         */
        switchName: pulumi.Input<string>;
        /**
         * Trigger a resource replacement on changes to any of these values. The
         * trigger values can be of any type. If a value is different in the current update compared to the
         * previous update, the resource will be replaced, i.e., the "create" command will be re-run.
         * Please see the resource documentation for examples.
         */
        triggers?: pulumi.Input<any[]>;
        /**
         * The command to run on update, if empty, create will 
         * run again. The environment variables PULUMI_COMMAND_STDOUT and PULUMI_COMMAND_STDERR 
         * are set to the stdout and stderr properties of the Command resource from previous 
         * create or update steps.
         */
        update?: pulumi.Input<string>;
        /**
         * VLAN ID for the network adapter. If not specified, no VLAN tagging is used.
         */
        vlanId?: pulumi.Input<number>;
        /**
         * Name of the virtual machine to attach the network adapter to
         */
        vmName?: pulumi.Input<string>;
        /**
         * VMQ weight for the network adapter. A value of 0 disables VMQ.
         */
        vmqWeight?: pulumi.Input<number>;
    }
}
